//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChainOfStores.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STORE()
        {
            this.SUPPLY = new HashSet<SUPPLY>();
        }
    
        public int IDstore { get; set; }
        public string NameStore { get; set; }
        public string Address { get; set; }
        public int NumberStore { get; set; }
        public string AuthorizedCapital { get; set; }
        public int ownerID { get; set; }
        public int IDprofile { get; set; }
    
        public virtual OWNER OWNER { get; set; }
        public virtual PROFILE PROFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLY> SUPPLY { get; set; }
    }
}
