//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_work_3_0.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime DATEOFBIRTH { get; set; }
        public string MARITALSTATUS { get; set; }
        public int IDGROUP { get; set; }
        public string COURSE { get; set; }
        public System.DateTime YEAROFENROLLMENT { get; set; }
        public int SCHOLARSHIP { get; set; }
    
        public virtual GROUP GROUP { get; set; }
    }
}
