//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airport.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class airportEntities : DbContext
    {
        public airportEntities()
            : base("name=airportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<citizenship> citizenship { get; set; }
        public virtual DbSet<flight> flight { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<passengers> passengers { get; set; }
        public virtual DbSet<plane> plane { get; set; }
        public virtual DbSet<Point> Point { get; set; }
    }
}
