//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flight()
        {
            this.passengers = new HashSet<passengers>();
        }
    
        public string FlifhtId { get; set; }
        public int distance { get; set; }
        public int departurePoint { get; set; }
        public int pointOfArrival { get; set; }
        public System.DateTime departureDate { get; set; }
        public System.DateTime arrivalDate { get; set; }
        public int TicketsSold { get; set; }
        public int IDplane { get; set; }
    
        public virtual Point Point { get; set; }
        public virtual plane plane { get; set; }
        public virtual Point Point1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<passengers> passengers { get; set; }
    }
}
