//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace airport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class passengers
    {
        public int id { get; set; }
        public string surName { get; set; }
        public string lastName { get; set; }
        public string MaddleName { get; set; }
        public string genderID { get; set; }
        public int passportID { get; set; }
        public int citizenshipID { get; set; }
        public string idFlight { get; set; }
    
        public virtual citizenship citizenship { get; set; }
        public virtual flight flight { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
