CREATE DATABASE [STUDENTS]

USE [STUDENTS]


CREATE TABLE [students](

	[ID]				INT IDENTITY (1,1)																																	NOT NULL,
	[NAME]				NVARCHAR(MAX)																																		NOT NULL,
	[DATEOFBIRTH]		DATE																																				NOT NULL,
	[MARITALSTATUS]		NVARCHAR(MAX)																																		NOT NULL,
	[IDGROUP]			INT			CONSTRAINT FK_students_IDGROUP_GROUP_GROUPID FOREIGN KEY REFERENCES [GROUP]([GROUPID])          										NOT NULL,
	[COURSE]			NVARCHAR(5)																																			NOT NULL,
	[YEAROFENROLLMENT]	DATE																																				NOT NULL,
	[SCHOLARSHIP]		INT																																					NOT NULL,
	CONSTRAINT PK_student_ID PRIMARY KEY([ID])

)
GO


CREATE TABLE [FACULTY](

	[FACULTYID]		INT IDENTITY(1,1)																																		NOT NULL,
	[TITLE]			NVARCHAR(MAX)																																			NOT NULL,
	[PLACES]		INT																																						NOT NULL,
	CONSTRAINT PK_FACULTY_FACULTYID PRIMARY KEY ([FACULTYID])
)
GO

CREATE TABLE [SPECIALTY](

	[SPECIALTYID]	INT IDENTITY(1,1)																																		NOT NULL,
	[TITLE]			NVARCHAR(MAX)																																			NOT NULL,
	[IDFACULTY]		INT		CONSTRAINT	FK_SPECIALTY_IDFACULTY_FACULTY_FACULTYID	FOREIGN KEY REFERENCES [FACULTY]([FACULTYID])											NOT NULL,
	CONSTRAINT PK_SPECIALTY_SPECIALTYID PRIMARY KEY([SPECIALTYID])

)
GO


CREATE TABLE [GROUP](

	[GROUPID]	INT IDENTITY(1,1)																																			NOT NULL,
	[TITLE]		NVARCHAR(MAX)																																				NOT NULL,
	[QUANTITY_STUDENTS] INT																																					NOT NULL,	
	[IDSPECIALTY]		INT		CONSTRAINT	FK_GROUP_IDSPECIALTY_GROUP_SPECIALTYIS	FOREIGN KEY REFERENCES [SPECIALTY]([SPECIALTYID])										NOT NULL,
	CONSTRAINT PK_GROUP_GROUPID PRIMARY KEY ([GROUPID])
	
)
GO

INSERT INTO [GROUP]([TITLE], [QUANTITY_STUDENTS], [IDSPECIALTY]) VALUES ('2-ИСП-9-1', '32', '1')
INSERT INTO [GROUP]([TITLE], [QUANTITY_STUDENTS], [IDSPECIALTY]) VALUES ('2-БТС-8-2', '27', '2')
INSERT INTO [GROUP]([TITLE], [QUANTITY_STUDENTS], [IDSPECIALTY]) VALUES ('3-ИСП-9-3', '23', '1')
INSERT INTO [GROUP]([TITLE], [QUANTITY_STUDENTS], [IDSPECIALTY]) VALUES ('5-БТС-8-2', '30', '2')
INSERT INTO [GROUP]([TITLE], [QUANTITY_STUDENTS], [IDSPECIALTY]) VALUES ('109 АП', '30', '6')
INSERT INTO [GROUP]([TITLE], [QUANTITY_STUDENTS], [IDSPECIALTY]) VALUES ('108 АП', '28', '6')

INSERT INTO [SPECIALTY]([TITLE], [IDFACULTY]) VALUES ('Информационные системы и программирование', '1')
INSERT INTO [SPECIALTY]([TITLE], [IDFACULTY]) VALUES ('вчкеаурпцофлипктопьвир.бп', '2')
INSERT INTO [SPECIALTY]([TITLE], [IDFACULTY]) VALUES ('мрачытипвабоыбюрмо лбсиато са', '3')
INSERT INTO [SPECIALTY]([TITLE], [IDFACULTY]) VALUES ('АПП', '4')

INSERT INTO [FACULTY]([TITLE], [PLACES]) VALUES ('Программирование', '6')
INSERT INTO [FACULTY]([TITLE], [PLACES]) VALUES ('Экономисты', '5')
INSERT INTO [FACULTY]([TITLE], [PLACES]) VALUES ('Бухгалтеры', '2')
INSERT INTO [FACULTY]([TITLE], [PLACES]) VALUES ('АП', '4')


SELECT * FROM []

DROP TABLE [GROUP], [students], [SPECIALTY], [FACULTY]