//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignIn
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string IDrole { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
